#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/platform/`uname -m`/sbin 
export PATH 

HOSTNAME=`hostname`
DOMAIN=`domainname`
case `uname -s` in 
                 Linux) 
			OS=`uname -rs`
			CSGREL=`cat /etc/csg_release | grep "CSG patch" | tail -1 | awk '{print $NF}' `
			HW=`uname -i`
#                         VENDOR=`dmidecode | grep "Manufacturer:" `
#                        PRODUCT=`dmidecode | grep "Product Name:" | head -1 | sed -e 's/^	//g ' | sed -e 's/Product Name: //g' |sed -e 's/^ +//g' ` 
                        PRODUCT=`dmidecode | grep "Product Name:" | head -1 | sed -e 's/^	*//g' | sed -e 's/Product Name: //g' ` 
                        CPU=`cat /proc/cpuinfo | grep "model name" | sort -u  | awk -F":" ' { print $2 }' | sed -e 's/^ *//g'`
                        CPUNUM=`cat /proc/cpuinfo | grep "processor" | wc -l `
                        MEMORY=`cat /proc/meminfo | head -1 | awk -F" " ' { printf "%s %s",$2,$3 } '` 
                        HOSTID=`hostid`
			SN=`dmidecode | grep "Serial Number:" | head -1 | sed -e 's/	*//g' | sed -e 's/Serial Number: //g' `
                        NUMINTERFACE=` ip a s | egrep "eth|bond" | egrep -v "ether|inet" | awk -F" " ' { print $2 } ' | wc -l `
			scsi_host=/sys/class/scsi_host
			fc_host=/sys/class/fc_host
			hba_count=0
			if [ -x /sys/class/fc_host ] ; then
        			for i in `ls -A /sys/class/fc_host` ; do
                			hba_count=`expr $hba_count + 1`
        			done
			elif [ -x  /sys/class/scsi_host ] ; then
        			for i in `ls -A /sys/class/scsi_host` ; do
                			hba_count=`expr $hba_count + 1`
        			done
			fi
                        if [ -e /etc/SuSE-release ] ; then 
				OSBRAND=`cat /etc/SuSE-release | grep VERSION | awk -F " " ' { print $3 } ' `
				OSPATCH=`cat /etc/SuSE-release | grep PATCHLEVEL | awk -F " " ' { print $3 } '`
				echo "$HOSTNAME;$DOMAIN;$OS;SLES;$OSBRAND;$OSPATCH;$CSGREL;$HW;$PRODUCT;$CPU;$CPUNUM:$MEMORY;$hba_count;$NUMINTERFACE;$HOSTID;$SN"
                        elif [ -e  /etc/redhat-release ] ; then 
                                OSBRAND=`cat /etc/redhat-release | head -1 ` 
                                OSPATCH="" 
				echo "$HOSTNAME;$DOMAIN;$OS;REDHAT;$OSBRAND;$OSPATCH;$CSGREL;$HW;$PRODUCT;$CPU;$CPUNUM;$MEMORY;$hba_count;NUMINTERFACE;$HOSTID;$SN"
                        fi 
                        ;;
                 SunOS) 
			OS=`uname -rs`
			CSGREL=`cat /etc/csg_release | grep "CSG patch" | tail -1 | awk '{print $NF}' `
			HW=`uname -p`
			PRTCONF=`prtconf -V`
			SOL_RELEASE=`cat /etc/release | head -1 | sed -e 's/^ *//g'`
			OSBRAND=""
                        OSPATCH=`uname -v`
#                        CPU=`prtdiag -v | grep "System Configuration:" | awk -F":" ' { print $2 } ' | sed -e 's/Sun Microsystems//g' | sed -e 's/sun4[uvs]//g' | sed -e 's/^ *//g' `
                        CPU=`psrinfo  -v | grep "," | sed -e 's/ /@/g' | awk -F"@" ' { print $8 $9 } ' | sed -e 's/,//g'| sort -u`
                        CPUNUM=`psrinfo | wc -l | sed -e 's/^ *//g`
                        HOSTID=`hostid`
                        MEMORY=` prtconf -vp | grep "Memory size:" | awk -F":" '{ print $2 $3 } ' | sed -e 's/^ //g'`
                        if [ -x /usr/sbin/fcinfo ] ; then 
                           NUMHBA=`fcinfo hba-port -l  | grep HBA | wc -l` 
                        elif [ -x /usr/sbin/lpfc/lputil ] ; then 
                            NUMHBA=`echo 0 | /usr/sbin/lpfc/lputil | grep "Emulex Fibre Channel" | awk -F":" ' { print $2 } ' | sed -e 's/^ *//g`
                        else 
				NUMHBA=0
                        fi                
                        PRODUCT=`eeprom | grep banner-name | awk -F"=" ' { print $2 } '`
                        NUMINTERFACE=`ifconfig -a | egrep 'hme|eri|bge|ce|ge|nxge|e1000g' | awk -F":" ' { print $1 } '  | sort -u | wc -l  | sed -e 's/ *//g`
			echo "$HOSTNAME;$DOMAIN;$OS;Solaris;$OSBRAND;$OSPATCH;$CSGREL;$HW;$PRODUCT:$CPU;$CPUNUM;$MEMORY;$NUMHBA;$NUMINTERFACE;$HOSTID"
			;;
esac 
