#!/bin/sh
SLOTLIST=$(hpacucli ctrl all show | \
grep Slot | sed -e 's/^.*Slot //g' -e 's/ .*$//g')
for i in $SLOTLIST
do
echo -n "`hostname`",`hpacucli ctrl slot=$i ld all show status | grep -v "^$" | sed -e 's/^ *//g'`
echo
echo -n "`hostname`",`hpacucli ctrl slot=$i pd all show status | grep -v "^$" | sed -e 's/^ *//g'`
echo
done
