#!/bin/bash 
for i in `cat U`  ; do 
    echo -n "$i  "
    ( ping -c 2 $i-ilo.equity.csfb.com  > /dev/null 2>&1) &&  ./locfg.pl -s $i-ilo.equity.csfb.com -f  Get_Host_Power.xml | grep "HOST_POWER=" | sed -e 's/^ *//g'
done 
