- hosts: e-10-4
  connection: local
  gather_facts: no
  tasks:
    - name: "Get Dell EMC OS9 Show version"
      dellos9_command:
      commands: ['show version']
      provider: "{{ cli }}"
      register: show_ver
    - debug: var=show_ver
