#!/bin/bash 
PATH=/sbin:/bin:/usr/sbin:/usr/sbin:/usr/ccs/bin:/usr/local/bin:/opt/VRTSvcs/bin 
export PATH 
haconf -makerw 
hares -modify ntfr SmtpRecipients  "gsiunixprodsupam@excham.csfb.com" SevereError
haconf -dump -makero 
